<?php

//error_reporting(E_ALL);
//ini_set('display_errors', TRUE);
//ini_set('display_startup_errors', TRUE);
//phpinfo(); exit();

//session_start();
require_once('../../config.php');
$path = $_SERVER["DOCUMENT_ROOT"] . GLOBAL_RACINE . 'Library';
set_include_path(get_include_path() . PATH_SEPARATOR . $path);
$path = './Library';
set_include_path(get_include_path() . PATH_SEPARATOR . $path);
require_once '../../Models/user/WebAppRoleGCD.php';
require_once '../../Models/user/WebAppPermGCD.php';
require_once '../../Models/user/WebAppUserGCD.php';
/** Include PHPExcel */
require_once '../../Library/PHPExcel/Classes/PHPExcel.php';
require_once '../../Models/Site.php';
require_once '../../Models/Core.php';
require_once '../../Library/connect_database.php';
require_once '../../Library/database.php';
//if ($_SESSION['gcd_user_role'] == WebAppRoleGCD::SUPERADMINISTRATOR || $_SESSION['gcd_user_role'] == WebAppRoleGCD::ADMINISTRATOR || $_SESSION['gcd_user_role'] == WebAppRoleGCD::CONTRIBUTOR){    

    // on vérifie qu'on a des valeurs en paramètres
    if (isset($_GET['is']) && isset($_GET['ic']) && isset($_GET['u']) && isset($_GET['a']) ){//xli 16-6
        $id_site = $_GET['is'];
        $id_core = $_GET['ic'];
        $id_data_source = $_GET['ds'];
        $id_method = $_GET['m'];
        $id_units = $_GET['u'];
        $id_age_method = $_GET['a'];
        $publis = explode(',', $_GET['pu']);
        $authors = explode(',', $_GET["au"]);

        //TODO // vérifier que tous les id sont numériques
        //
        // on vérifie que le site et la carotte existe et on récupère les noms
        $site = SITE::getObjectPaleofireFromId($id_site);
        $core = CORE::getObjectPaleofireFromId($id_core);
        $data_source = DataSource::getObjectPaleofireFromId($id_data_source);
        $method = CharcoalMethod::getObjectPaleofireFromId($id_method);
        $units = CharcoalUnits::getObjectPaleofireFromId($id_units);
        $age_model_method = AgeModelMethod::getObjectPaleofireFromId($id_age_method);

        // on vérifie que les publis existent
        foreach($publis as $id_pub){
            if (empty(Publi::getObjectPaleofireFromId($id_pub))){
                $id_pub = null;
            }
        }
        $publis = array_filter($publis);
        // on vérifie que les auteurs existent
        foreach($authors as $id_contact){
            if (empty(Contact::getObjectFromStaticList($id_contact))){
                $id_contact = null;
            }
        }
        $authors = array_filter($authors);
        

        if ($site != NULL && $core != NULL && $units != NULL && $age_model_method != NULL){
            // Create new PHPExcel object
            $objPHPExcel = new PHPExcel();

            // Set document properties
            $objPHPExcel->getProperties()->setCreator("GCD Paleofire")
                ->setLastModifiedBy("GCD Paleofire")
                ->setTitle("File template for samples integration")
                ->setSubject("File template for samples integration")
                ->setDescription("File template for samples integration generated by palefire.org")
                ->setKeywords("template samples xlsx");

            // ajout des paramètres en page 2
            $sheet = new PHPExcel_Worksheet(null, 'Parameters');
            /*$objPHPExcel->addSheet($sheet, 1);
            $activeSheet = $objPHPExcel->setActiveSheetIndex(1);
            $activeSheet ->setCellValue('A1', "Parameters");
            $activeSheet ->setCellValue('A2', "Charcoal size");
            $listeSize = CharcoalSize::getAllCharcoalSizeByCHARCOAL_SIZE_CODE();
            $listeDesc = null;
            $i = 3;
            /$plageValidationSize = 'Parameters!$A$'.$i;
            foreach( $listeSize as $eltSize ){
                $activeSheet ->setCellValue('A'.$i, $eltSize['CHARCOAL_SIZE_DESC']);
                $i++;
            }
            $plageValidationSize .= ':$A$'.$i;
            */
            
            // Add some data
            $activeSheet = $objPHPExcel->setActiveSheetIndex(0);
            $data_source_name = "";
            if ($data_source != NULL) $data_source_name = $data_source->getName();
            $method_name = "";
            if ($method != NULL) $method_name = $method->getName();
            $activeSheet ->setCellValue('A1', "File template for samples integration\n" 
                    /*."Site : ".$site->getName()." (".$id_site .")\n"
                    ."Core : ".$core->getName()." (".$id_core.")\n"
                    ."Data source : ".$data_source->getName()." (".$id_data_source.")\n"
                    ."Method : ".$method->getName() . " (".$id_method.")\n"
                    ."Units : ".$units->getName() . " (".$id_units.")"*/
                    ."Site : ".$site->getName()."\n"
                    ."Core : ".$core->getName()."\n"
                    ."Data source : ".$data_source_name."\n"
                    ."Method : ".$method_name . "\n"
                    ."Units : ".$units->getName() . "\n"
                    ."Age model method : ".$age_model_method->getName()
                    )
                        ->mergeCells('A1:G1')
                        ->getRowDimension('1')->setRowHeight(115);
            $activeSheet->getStyle('A1')->getAlignment()->setWrapText(true);
            $activeSheet->setCellValue('A2','{"site":'.$id_site .','
                    .'"core":'.$id_core.','
                    .'"datasource":' . (($data_source == NULL)? 'null' : $id_data_source) .','
                    .'"method":' . (($method == NULL)? 'null' : $id_method) . ','
                    .'"units":'.$id_units.','
                    .'"agemethod":'.$id_age_method.','
                    .'"pubs":"'.implode($publis, ',').'",'
                    .'"authors":"'.implode($authors, ',').'"}' );
            
            $activeSheet//->setCellValue('A3', 'SAMPLE NAME') va être créé automatiquement
                        ->setCellValue('A3', 'DEPTH UP (cm)')
                        //->setCellValue('C3', 'DEPTH MIDLLE') va être calculé automatiquement
                        ->setCellValue('B3', 'DEPTH DOWN (cm)')                    
                        ->setCellValue('C3', 'AGE UP (cal BP)')
                        //->setCellValue('F3', 'AGE UP NEGATIVE ERROR')
                        //->setCellValue('G3', 'AGE UP POSITIVE ERROR')
                        ->setCellValue('D3', 'AGE DOWN (cal BP)')
                        ->setCellValue('E3', 'VOLUME (cm³)')
                        ->setCellValue('F3', 'CHARCOAL QUANTITY');
                        //->setCellValue('I3', 'AGE DOWN NEGATIVE ERROR')
                        //->setCellValue('J3', 'AGE DOWN POSITIVE ERROR');
            $activeSheet->getColumnDimension('A')->setWidth(20);
            $activeSheet->getColumnDimension('B')->setWidth(20);
            $activeSheet->getColumnDimension('C')->setWidth(30);
            $activeSheet->getColumnDimension('D')->setWidth(30);
            $activeSheet->getColumnDimension('E')->setWidth(30);
            $activeSheet->getColumnDimension('F')->setWidth(30);
            //$activeSheet->getColumnDimension('G')->setWidth(20);
            //$activeSheet->getColumnDimension('H')->setWidth(20);
            //$activeSheet->getColumnDimension('I')->setWidth(20);
            //$activeSheet->getColumnDimension('J')->setWidth(20);

            // ajout d'une liste déroulante pour la colonne size
            /*$objValidSize = new PHPExcel_Cell_DataValidation;
            $objValidSize->setType( PHPExcel_Cell_DataValidation::TYPE_LIST );
            $objValidSize->setFormula1($plageValidationSize);
            $objValidSize->setShowDropDown(true);
            for($i = 4; $i < 500; $i++){
                $activeSheet->getCell('E'.$i)->setDataValidation($objValidSize);
            }*/
            // Rename worksheet
            $objPHPExcel->getActiveSheet()->setTitle('Samples integration');

            // Set active sheet index to the first sheet, so Excel opens this as the first sheet
            $objPHPExcel->setActiveSheetIndex(0);

            // Redirect output to a client’s web browser
            header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
            header('Content-Disposition: attachment;filename="sample_template.xlsx"');
            header('Cache-Control: max-age=0');
        
            $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
            $objWriter->save('php://output');
            
            exit;
        } else {
            echo '<div class="alert alert-danger"><strong>Error recording !</strong></br>Site, core, units or age model must be selected.</div>';
        }
    }

